language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
script: mvn clean test
notifications:
  email:
    recipients:
      - "officialenkoded@gmail.com"
    on_success: change
    on_failure: always
